### ISSUE TITLE
Sensitive data in ConfigMaps and Helm values.yaml

### ISSUE THREAD

**Issue by pabloromeo** [FlowFuse/helm#114]
### Current Behavior

It would appear that the only mechanism for providing sensitive information such as database passwords and access keys, is through Helm's values file, which end up being embedded within a ConfigMap that generates the flowforge.yml config file, where passwords end up being stored in plaintext.
This sensitive information ideally should be managed through kubernetes secrets.

This is especially problematic if you are applying a GitOps approach, through tools such as ArgoCD or Flux for deploying this Chart.

### Expected Behavior

Ideally there should be a safe mechanism to provide references to secrets, such as database passwords.

A common pattern when dealing with Helm is that the templates themselves support not just providing the actual passwords in plaintext, but also support referencing an existing Kubernetes secret (created prior to the install of the chart) which is usually attached to the deployment as environment variables. But since here those values are used to generate a config file, things may be a bit more complicated, unless flowforge has support for getting sensitive values from elsewhere outside of flowforge.yml (such as environment variables for example).

### Environment

- FlowForge version:
- Node.js version:
- npm version:
- Platform/OS:
- Browser:

**Comment by roberttmoon-wizehive** [comment]
As a short term solution for this issue could we add a bypass to the ConfigMap and allow it to be written by hand in a k8s secret?

**Comment by hardillb** [comment]
@roberttmoon-wizehive I'm not sure what you mean here.

FlowForge needs to read all the values from a single `flowforge.yml` file. That is currently provided to the deployment from the ConfigMap.

If you can come up with a PR to the helm chart that moves to a Secret then I'll happily review it, but it will need to support upgrades.

**Comment by roberttmoon-wizehive** [comment]
np np, I'm putting together a PR that explains what I'm thinking.

**Comment by roberttmoon-wizehive** [comment]
> If you can come up with a PR to the helm chart that moves to a Secret then I'll happily review it, but it will need to support upgrades.

How is that secret set, I don't see it in the helm charts

**Comment by hardillb** [comment]
@roberttmoon-wizehive There is no secret, hence the issue...

**Comment by roberttmoon-wizehive** [comment]
this is the secret it uses, but I don't know where it is created:
> https://github.com/flowforge/helm/blob/main/helm/flowforge/templates/job-upgrade-db.yaml#L37-L41

there doesn't seem to be anything in the chart the creates the secret.

**Comment by roberttmoon-wizehive** [comment]
oh its from the postgresql chart

**Comment by roberttmoon-wizehive** [comment]
Ok, so i have looked over the db update script some more and it seems that the update only runs when you are using `fileStorage` and `localPostgres`.

My expectation would be that if you were by-pasing the config builder in the helm chart to write your own from scratch as a Kubernetes secret then you would be beyond running postgres in your cluster. 

The goal here is to provide a method (albeit not as user friendly as I would like) to secure the helm chart and make it safe to check in to a source control repository and be installed to your cluster with something like ArgoCD or Flux.

Additionally, I could add a validation to the chart.schema.json that prevents using the secrets with the localPostgres

**Comment by ppawlowski** [comment]
Concerns reported in this issue have been recently fixed in our Helm chart. Some of them have already been released in the `2.1.0` version of our Helm chart. Please have a look at the chart's [documentation](https://github.com/FlowFuse/helm/blob/main/helm/flowforge/README.md) as well as the [changelog](https://github.com/FlowFuse/helm/releases/tag/v2.1.0) for the 2.1.0 release.
We plan to release further credentials-related improvements on the 14th of March 2024.
