### ISSUE TITLE
Helm install,  don't create: ExternalName if  forge.localPostrgresql == false

### ISSUE THREAD

**Issue by lukasz18dg** [FlowFuse/helm#143]
### Current Behavior

If forge.localPostrgresql == false, then helm create automatically create: ExternalName service.

### Expected Behavior

Don't create any service for Postgres database, the current behavior is problematic, because as far as I know, we can't use Postgress database ran on the same cluster, because Kubernetes will not resolve DNS request and provide all of them to host system.
Instead of creating Externall name, use directly all data provided in values file in flowforge container similar like in: goauthentik => https://github.com/goauthentik/helm

### Steps To Reproduce

Based on https://flowforge.com/docs/install/kubernetes/ , I tried to:
0. Using CloudNativePG Helm Chart ( https://github.com/cloudnative-pg/charts ) run kubernetes in different namespace
1. 
2. Executed command: 
> helm repo add flowforge https://flowforge.github.io/helm
> helm repo update
3. Exexuted command:
> kubectl label node <management node name> role=management
> kubectl label node <projects node name> role=projects
for my nodes in microk8s
4. Created like that values file:
forge:

>   entryPoint: forge.<censored, my domain>
>   domain: <censored, my domain>
>   https: false
>   localPostgresql: false
>   projectNamespace: flowforge
>   postgres:
>     host: postgresql-pvc-rw.psql
>     dbUsername: forge
>     dbName: flowforge
>     dbPassword: <password>
>     port: 5432
>   telemetry:
>     enabled: false
>   fileStore:
>     enabled: false

postgresql-pvc-rw.psql << name of service from step 0 and name of namespace/

and executed:

> helm upgrade --atomic --install flowforge flowforge/flowforge -f valuesforge.yaml

### Environment

- FlowForge version: v1.8.1
- Node.js version: Unknown, helm version:
- npm version: Unknown, helm version:
- Platform/OS: Ubuntu 20.4
- Browser: None.

**Comment by ppawlowski** [comment]
We removed an `ExternalName` service type from our Helm chart. At this moment connection to the database host is performed directly from the pod. Database hostname is customized via the `postgresql.host` chart value. This approach allows one to connect to the Kubernetes resource in a different namespace without a need to specify its FQDN.
This feature will be introduced to the public in the next chart release which should take place on the 14th of March 2024.
