### ISSUE TITLE
Helm install finished with failed status due to too low version of Postgres

### ISSUE THREAD

**Issue by lukasz18dg** [FlowFuse/helm#144]
### Current Behavior

Helm install finished with failded status:

> Error: release flowforge failed, and has been uninstalled due to atomic being set: context deadline exceeded

on Oracle Cloud ARM Free Tier machine

Looking in logs from Postgres pod, I see something like this:

> exec /opt/bitnami/scripts/postgresql/entrypoint.sh: exec format error

If I correctly understood the issue: https://github.com/bitnami/charts/issues/15140 , it is missing ARM support in the lower version of Postgres.

### Expected Behavior

1. Upgrade Postgres version or let me decide which version I want to use OR
2. Automatically ( Dependabot ? ) update dependencies?
3. Add information about the tested version of Postgres where Flowforge works correctly

### Steps To Reproduce

1. Installed Kubernetes ( microk8s ) on Oracle Cloud Free Tier ARM images.
2. Based on: https://flowforge.com/docs/install/kubernetes/#configure-flowforge  Execute commands:

> helm repo add flowforge https://flowforge.github.io/helm
> helm repo update
> kubectl label node role=management
> kubectl label node role=projects
> for my nodes in microk8s

3. Created like that values file:

> forge:
> entryPoint: forge.<censored, my domain>
> domain: <censored, my domain>
> https: false
> localPostgresql: true
> projectNamespace: flowforge
> telemetry:
> enabled: false
> fileStore:
> enabled: false

and executed:

> helm upgrade --atomic --install --timeout 10m flowforge flowforge/flowforge -f valuesforge.yaml

4. After a while execute:

> kubectl get all
> kubectl logs pod/<name-of-pod-with-psql>

> exec /opt/bitnami/scripts/postgresql/entrypoint.sh: exec format error

### Environment

- FlowForge version: version: v1.8.1
- Node.js version: Unknown, helm version
- npm version: Unknown, helm version
- Platform/OS: Ubuntu 20.04
- Browser: None

**Comment by hardillb** [comment]
We don't support installing on arm at this time

**Comment by lukasz18dg** [comment]
In other words, even:
- If I have external Postgres with 15, then Flowforge will be not working due to a problem with "initializes the db on startup"
- If I have ARM machines, then none version local Postgres 14 or 10 of Flowforge will be not working, due to low version PSQL
- If I correctly understood, my only hope is to find some external Postgres 14, where Flowforge will be connected ( not on ARM)

How overcomplicated and missing information about the supported version :(.

**Comment by hardillb** [comment]
- You can manually setup to the database with PostgreSQL 15 (create the DB and user and pass the details to the helm chart)
- The helm chart can not currently automatically setup a PostgreSQL 15 DB hence why the included bitnami chart is pinned at 14
- The bitnami support for ARM64 is very new, we haven't had the time to test them yet.
- You can run a multi arch K8s cluster and run the DB on x86_64 and the rest of ARM64 (this is very similar to how we run the SaaS instance)

Please feel free to see if you can supply a pull request to add support for PostgreSQL 15
