### ISSUE TITLE
Update postgresql chart version to `11.9.13`

### ISSUE THREAD

**Issue by ppawlowski** [FlowFuse/helm#219]
### Description

Upgrade postgresql chart version to `11.9.13` + test if application is running properly after the update.

### Epic/Story

#223

**Comment by ppawlowski** [comment]
I have successfully installed and configured the Forge app locally after updating the Postgresql chart dependency to `11.9.13`. 

Requirements:
* kind
* helm

Performed steps:
* Create Kubernetes cluster with `kind` using [customized config](https://zerobin.org/?213831c0b212b49f#EFsKidqkND8SbWtrBunbGejcL93uRW72121SmTVA4a6a) and [nginx-ingress installed](https://kind.sigs.k8s.io/docs/user/ingress/#ingress-nginx)
* Install the app using the helm chart:
```
helm upgrade --install --namespace default --atomic --set forge.domain='flowfuse.local.gd' --set postgresql.global.storageClass='standard' flowforge ./helm/flowforge
```

After installation, I was able to:
* perform initial setup
* log in
* create a team
* create an application
* create a stack
* create applications using both stacks

**Comment by hardillb** [comment]
Deffered to v2.0.0 release
