### ISSUE TITLE
Ingress object should be created conditionally 

### ISSUE THREAD

**Issue by ppawlowski** [FlowFuse/helm#226]
With default chart values, the creation of an ingress object fails with the error:
```
Error: INSTALLATION FAILED: 1 error occurred:
	* Ingress.extensions "flowforge-ingress" is invalid: spec.rules[0].host: Invalid value: "forge.": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
```

We should either provide some proper default values or create an ingress object only if `forge.domain` or `forge.entryPoint` have values.

**Comment by hardillb** [comment]
This is deliberate, the system won't work without a valid domain and every install will have it's own bespoke domain, so failing if it's not set is correct (the `values-schema.json` should have it marked as required so it should fail before trying to render the templates, if it doesn't that is the fix here)

**Comment by ppawlowski** [comment]
In YAML if a key doesn't have a value it will be set to an empty string. I have created a PR which introduced validation of this field.  

> the system won't work without a valid domain  (...) , so failing if it's not set is correct

I can't really argue with that. I will close this issue once a related PR is merged.
