### ISSUE TITLE
helm chart needs improvements

### ISSUE THREAD

**Issue by fvogl** [FlowFuse/helm#268]
### Description

Some enhancements are required for the helm chart
- the DB password (especially for localPostgresql=false) should not be provided in the values file (use something like existing secret) and clearly it should not be stored in a configmap
- the db.host should be taken from .Values.forge.postgres.host if localPostgresql=false
- the deployment should have configurable additional labels and the securityContext also needs to be taken from values
- same would be required for the deployment that is created for an instance (pod label + securityContext) so it can be configured to work on OpenShift

**Comment by hardillb** [comment]
@ppawlowski can you consider these when making the helm 2.0 changes. Thanks

**Comment by corentin-pasquier** [comment]
Hello,
I also find a problem when you try to change the database name (wanted to change it from flowforge to flowfuse, trying with postgresql).
The Helm chart is setting a db.db value in the flowforge.yml config-map: https://github.com/FlowFuse/helm/blob/main/helm/flowforge/templates/configmap.yaml#L27
However Flowfuse is looking for a db.database value in the code: https://github.com/FlowFuse/flowfuse/blob/main/forge/db/index.js#L51

With this problem, the database name is always flowforge.

I can create a news issue if you want.

**Comment by hardillb** [comment]
@corentin-pasquier that's a typo that got missed in review, PR opened to fix, thanks for the pointer

**Comment by hardillb** [comment]
@corentin-pasquier PR has been merged

**Comment by ppawlowski** [comment]
The latest version (`2.1.0`) of our Helm chart introduced the requested features. Please have a look at the chart's [documentation](https://github.com/FlowFuse/helm/blob/main/helm/flowforge/README.md) as well as the [changelog](https://github.com/FlowFuse/helm/releases/tag/v2.1.0) for the `2.1.0` release.
