### ISSUE TITLE
Add possibility to use external secret with database credentials

### ISSUE THREAD

**Issue by ppawlowski** [FlowFuse/helm#290]
### Description

As a Kubernetes cluster operator, I would like to have the possibility to create a secret with database credentials on my own and pass the secret name to the helm chart as a value. 
Secret should be utilised for:
* application cofiguration
* database configuration (if local database setup is selected)

### Related tasks

#268

**Comment by hardillb** [comment]
We should include the option to also supply SMTP email credentials as an existing secret.

Using the template init container this should be possible.
