### ISSUE TITLE
As an OPS I would like to have a possibility to customize domain for the broker

### ISSUE THREAD

**Issue by ppawlowski** [FlowFuse/helm#295]
### Description

At this moment domain for the broker is fixed - it will be always deployed on `mqtt.$forge.domain` domain.
As an OPS I would like to have the possibility to specify a domain for the broker service on my own.
@hardillb please share your thoughts. 

This feature will also enable deployment of MQTT brokers into our staging environments, without the hard-coded ties of the existing domain configuration.

**Comment by hardillb** [comment]
This will need some detailed thought.

The broker we deploy is not (currently) available for general purpose MQTT usage, it is very heavily locked down and tightly coupled to the authentication endpoints we have in the forge app.

While we could choose to host it on a different hostname/domain it is still going to need to be the version of mosquitto configured with the tight auth plugin to work, not a different broker hosted outside the control of FF.

Assuming this is just a change to the hostname/domain it will also need to be passed to the forge app via the flowforge.yml as this value needs to be passed to devices and instances as part of configuration.

**Comment by ppawlowski** [comment]
> Assuming this is just a change to the hostname/domain it will also need to be passed to the forge app via the flowforge.yml as this value needs to be passed to devices and instances as part of configuration.

That is the only change I was thinking about. No changes to the broker itself were planned.

**Comment by hardillb** [comment]
OK, low priority unless it's actively breaking something (I assume this is from the pr deploy stuff Steve asked about)

**Comment by ZJvandeWeg** [comment]
@MarianRaphael @joepavitt Can you update the description with how this factors in with the CD that's now blocked? The description makes it sound like a nice to have.
