### ISSUE TITLE
ci: On release, `CHANGELOG.md` file is not updated

### ISSUE THREAD

**Issue by ppawlowski** [FlowFuse/helm#346]
### Current Behavior

The Helm chart release pipeline does not update the `CHANGELOG.md` file. Proper content is visible on the release page, though.

### Expected Behavior

Changelog file should be updated too.
Possible solution: use https://github.com/semantic-release/git .

### Steps To Reproduce

1. Execute release pipeline
2. Check the content of `CHANGELOG.md`

### Environment

N/A

**Comment by Piwero** [comment]
This line is pointing to a wrong path. https://github.com/FlowFuse/helm/blob/main/.releaserc#L28
Changelog file doesn't exist inside of that directory but in the root. https://github.com/FlowFuse/helm/pull/385
