### ISSUE TITLE
Generate Node-RED 4.x container

### ISSUE THREAD

**Issue by knolleary** [FlowFuse/helm#350]
With Node-RED 4.x Beta.1 now available, we should do the work to get the 4.x stream available on FF Cloud.

First step is adding it to the container build here.

**Comment by ppawlowski** [comment]
Pipelines for building both internal (AWS ECR) and public (Docker Hub) container images have been created. A private image has been built and used to create a new stack type on the FlowFuse Cloud platform (production).
