### ISSUE TITLE
Helm chart licence confusion

### ISSUE THREAD

**Issue by riceo** [FlowFuse/helm#460]
### Description

Hi,

I noticed that the Helm chart seems to be covered by the [`Flowfuse licence`](https://github.com/FlowFuse/helm/blob/main/helm/flowforge/LICENSE
) rather than Apache. Unless I'm misreading, this suggests I require a paid subscription in order to use the helm chart, even though I'd be deploying open source software. 

Is this intentional or an oversight?

Thanks!

**Comment by hardillb** [comment]
@riceo The Helm Chart is free to use, it will install the OpenSource version of FlowFuse (Enterprise features will be enabled after adding a license). A PR is open to update the license on the Helm Chart and a new version will be published when it's merged.
